version: '2'
services:
    solarsystem-app:
        image: solarsystem
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://solarsystem-postgresql:5432/solarSystem
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    solarsystem-postgresql:
        extends:
            file: postgresql.yml
            service: solarsystem-postgresql
